# this is a comment
podName="${groupidStandardized}-pod-template"
podVolume="volume-${groupidStandardized}"
nfsVolumePath="/path/on/server"
nfsServer=nfsServer.sas.com
podMountPath="${groupNameStandardized}"
