---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: delete-pgo-role-nsadmin
patch: |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: pgo-role
    namespace: ${NAMESPACE}
  $patch: delete
