apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../staging/compute

patchesJson6902:
- target:
    kind: PodTemplate
    version: v1
    namespace: dev
    name: sas-compute-job-config
  path: create-pod-template.yaml
